### ISSUE TITLE
Cant load any sc's

### ISSUE THREAD

**Issue by nosebs** [danila-schelkov/sc-editor#20]
[log.txt](https://github.com/danila-schelkov/sc-editor/files/14548710/log.txt)

example:
[events.zip](https://github.com/danila-schelkov/sc-editor/files/14548719/events.zip)
[loading.zip](https://github.com/danila-schelkov/sc-editor/files/14548720/loading.zip)

**Comment by danila-schelkov** [comment]
Оh... I forgot to add support for the new texture tag. An update will be coming as soon as possible.
