### ISSUE TITLE
Freeing textures from memory

### ISSUE THREAD

**Issue by Daniil-SV** [danila-schelkov/sc-editor#22]
When changing the window size (opening to full screen mode and vice versa), it seems that all textures are freed from memory and become just black
![image](https://github.com/danila-schelkov/sc-editor/assets/54799334/1e110dcc-1655-42fc-b26c-da91ec9e63a9)
![image](https://github.com/danila-schelkov/sc-editor/assets/54799334/21c2d666-482e-44a2-955a-7dde4abef8f6)

**Comment by Daniil-SV** [comment]
I just open the file, then click on the middle button in corner to set full screen mode and that's it, all textures turn black

**Comment by danila-schelkov** [comment]
Is the bug still relevant? There's been a lot of changes since the last comment on this issue

**Comment by Daniil-SV** [comment]
at least I haven't encountered this recently
so apparently this bug is not relevant now

**Comment by danila-schelkov** [comment]
Thank you for your response. I'm closing this issue
